name: "Dev Release"

on: [workflow_dispatch]

jobs:
  release:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: node
        uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/

      - name: Install
        run: npm install --save-dev @babel/cli @babel/core @babel/preset-env @babel/preset-typescript babel-plugin-add-module-exports typescript @types/node

      - name: build
        run: node build.js
      
      - name: build declarations
        run: npm run tscbuild

      - name: publish
        run: |
          npm version --git-tag-version=false $(jq --raw-output '.version' package.json).$(date +%s)
          npm publish --tag dev || true --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}