name: Docs

on: [workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Download
      run: npm i typedoc

    - name: Build
      run: npm run docsbuild